### ISSUE TITLE
The export File function does not work

### ISSUE THREAD

**Issue by lapd-viosoft** [Emurasoft/excel-csv-import#39]
##  Environment 1
- Platform: Mac
- Host: Excel
- Office version number: 16.30 (19101301)
- Operating System: MacOS catalina

##  Environment 2
- Platform: Windows 
- Host: Excel
- Office version number: 1912 ( Build 12325.20288)
- Operating System: Windows 10

## Current Behavior
- I tried to export the current sheet as CSV by clicking "Export to CSV" button but nothing happen
- It is expected to see the dialog
-  If it does downloading automatically, which location should I check to see the exported file

Thanks

**Comment by MakotoE** [comment]
Sorry I wasn't getting notifications for this repo. I reproduced this in Excel for Windows 10.

**Comment by MakotoE** [comment]
#43

Thanks for bringing up this issue. It is a rather annoying bug. I came across this exact problem when I tested it on my Mac a while ago. https://github.com/OfficeDev/office-js/issues/471 It used to be fixed, but now it doesn't work on Mac and Windows.

The export to file feature has always worked on Excel Online, so do consider using that if you are able.

I disabled file exporting for desktop platforms because getting the JS file API to work properly with Excel is a nightmare.
